- type: entity
  name: handcuff box
  parent: BoxCardboard
  id: BoxHandcuff
  description: A box full of handcuffs.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: Handcuffs
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: handcuff

- type: entity
  name: ziptie box
  parent: BoxCardboard
  id: BoxZiptie
  description: A box full of zipties.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: Zipties
        amount: 9
  - type: Sprite
    layers:
    - state: box_security
    - state: ziptie

- type: entity
  name: flashbang box
  parent: BoxCardboard
  id: BoxFlashbang
  description: 'WARNING: These devices are extremely dangerous and can cause blindness or deafness in repeated use.'
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: GrenadeFlashBang
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang

- type: entity
  name: tear gas grenade box
  parent: BoxCardboard
  id: BoxTearGas
  description: A box full of tear gas grenades. Hold your breath.
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: TearGasGrenade
        amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang
