- type: entity
  parent: CrateSecgear
  id: CrateSecurityNonlethal
  name: nonlethals crate
  description: Contains a mix of disablers, stun batons, and flashes. Requires Security access to open.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: WeaponDisabler
          amount: 3
        - id: Stunbaton
          amount: 3
        - id: BoxFlashbang
        - id: Flash
          amount: 3
#        - Pepperspray
#        - GrenadeTeargas

- type: entity
  parent: CrateSecgear
  id: CrateSecuritySupplies
  name: security supplies crate
  description: Contains various supplies for the station's Security team. Requires Security access to open.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxHandcuff
        - id: BoxSechud
#        - SecBelt
#        - SecGasmask
#        - SpacelawBook

- type: entity
  parent: CrateSecgear
  id: CrateRestraints
  name: restraints crate
  description: Contains two boxes each of handcuffs and zipties. Requires Security access to open.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxHandcuff
          amount: 2
        - id: BoxZiptie
          amount: 2

- type: entity
  parent: CrateSecgear
  id: CrateSecNonlethalThrowables
  name: nonlethal throwables crate
  description: Contains one box each of flashbangs, stingers, tear gas grenades, and four bolas. Requires Security access to open.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxFlashbang
        - id: BoxStinger
        - id: BoxTearGas
        - id: Bola # replace with 4 e-bolas when added
          amount: 4
