- type: entity
  parent: CratePlastic
  id: CrateServiceJanitorialSupplies
  name: janitorial supplies crate
  description: Fight back against dirt and grime with Nanotrasen's Janitorial Essentials(tm)! Contains three buckets, caution signs, and cleaner grenades. Also has a single mop, broom, spray cleaner, wire brush, rag, and trash bag.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: AllSoapsTable
        - id: MopItem
        - id: MopBucketCubeWrapped
        - id: Bucket
          amount: 3
        - id: WetFloorSign
          amount: 2
        - id: SprayBottleSpaceCleaner
          amount: 2
        - id: TrashBag
          amount: 2
        - id: Plunger
          amount: 2

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceReplacementLights
  name: replacement lights crate
  description: May the light of Aether shine upon this station! Or at least, the light of twelve fluorescent light tubes and twelve incandescent light bulbs.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxLighttube
        - id: BoxLightbulb

- type: entity
  parent: CrateGenericSteel
  id: CrateMousetrapBoxes
  name: mousetraps crate
  description: Mousetraps, for when all of service is being haunted by an entire horde of rats. Use sparingly... or not.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxMousetrap

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceSmokeables
  name: smokeables crate
  description: Tired of a quick death on the station? Order this crate and chain-smoke your way to a coughy demise!
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:GroupSelector
          children:
          - id: CigCartonGreen
            weight: 0.50
          - id: CigCartonRed
        - !type:GroupSelector
          children:
          - id: CigCartonBlue
            weight: 0.50
          - id: CigCartonBlack
        - !type:GroupSelector
          children:
          - id: CigarGoldCase
            weight: 0.05
          - id: CigarCase
        - id: Matchbox
          amount: 2

- type: entity
  parent: CrateGenericSteel
  id: CrateServiceBureaucracy
  name: bureaucracy crate
  description: Several stacks of paper, a few pens and an office toy. What more could you ask for?
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: Paper
          amount: 12
        - id: PaperOffice
          amount: 6
        - id: Pen
          amount: 2
        - id: BoxFolderClipboardEmpty
          amount: 2
        - id: HandLabeler
        - id: BoxFolderBlueEmpty
        - id: BoxFolderRedEmpty
        - id: BoxFolderYellowEmpty
        - id: NewtonCradle
        - id: BoxEnvelope
        - id: BrbSign

- type: entity
  parent: CrateGenericSteel
  id: CrateCandles
  name: candles crate
  description: Contains 4 boxes of candles, 2 large and 2 small. For atmosphere or something.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxCandle
          amount: 2
        - id: BoxCandleSmall
          amount: 2
