- type: entity
  id: LockerBoozeFilled
  suffix: Filled
  parent: LockerBooze
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerBooze

- type: entityTable
  id: FillLockerBooze
  table: !type:AllSelector
    children:
    - id: ClothingOuterArmorBasicSlim
    - id: WeaponShotgunDoubleBarreledRubber
    - id: DrinkShaker
    - id: ClothingEyesHudBeer
    - id: HandLabeler
    - id: DrinkBeerBottleFull
      amount: !type:BinomialNumberSelector
        trials: 3
    - !type:AllSelector
      rolls: 2
      children:
      - id: BoxBeanbag
      - id: RagItem

- type: entity
  id: ClosetChefFilled
  suffix: Filled
  parent: ClosetChef
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetChef

- type: entityTable
  id: FillClosetChef
  table: !type:AllSelector
    children:
    - id: VariantCubeBox
    - id: SprayBottleWater
    - id: FoodBoxCloth
    - id: ReagentContainerSugar
    - id: FoodCondimentBottleEnzyme
    - id: DrinkSoyMilkCarton
    - !type:AllSelector
      rolls: 2
      children:
      - id: DrinkMilkCarton
      # really, milk should go in the fridge. Unfortunately saltern only has freezers.
      # yes, I'm using this as an excuse to not have to do extra work.
      - id: ReagentContainerFlour
      - id: BoxMousetrap
    - !type:AllSelector
      rolls: 3
      children:
      - id: FoodCondimentPacketSalt
      - id: FoodCondimentPacketPepper

- type: entity
  id: ClosetJanitorFilled
  suffix: Filled
  parent: ClosetJanitor
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetJanitor

- type: entityTable
  id: FillClosetJanitor
  table: !type:AllSelector
    children:
    - id: WetFloorSign
      amount: 3
    - id: LightReplacer
    - id: BoxLightMixed
    - id: Holoprojector
    - !type:AllSelector
      rolls: 2
      children:
      - id: MopItem
      - id: BoxMousetrap
      - id: TrashBag
      - id: SoapNT
      - id: FlashlightLantern
      - id: Plunger
      - id: WireBrush

- type: entity
  id: ClosetLegalFilled
  suffix: Filled
  parent: ClosetLegal
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetLegal

- type: entityTable
  id: FillClosetLegal
  table: !type:AllSelector
    children:
    - id: BriefcaseBrownFilled
      prob: 0.80
    - id: ClothingOuterRobesJudge
